# Programer: Pineapple
# 10/20/2020

version: "3.8"
services:
  portainer:
    container_name: Portainer
    image: portainer/portainer-ce:2.0.0
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  plex:
    container_name: Plex
    image: linuxserver/plex:version-1.20.2.3402-0fec14d92
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=america/chicago
    volumes:
      - /home/Data/Config/Plex:/config
      - /home/Data/Storage/Tv:/tv
      - /home/Data/Storage/Movies:/movies

  tautulli:
    container_name: Tautulli
    image: linuxserver/tautulli:7b936fd6-ls1
    restart: unless-stopped
    ports:
      - "8181:8181"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - TZ=america/chicago
    #  - TZ=america/new_york
    volumes:
      - /home/Data/Config/Tautulli:/config
      - /home/Data/Config/Plex/Library/Application Support/Plex Media Server/Logs/:/logs

  ombi:
    container_name: OMBI
    image: linuxserver/ombi:version-v4.0.530
    restart: unless-stopped
    ports:
      - "3579:3579"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/chicago
    #  - TZ=america/new_york
    volumes:
      - /home/Data/Config/OMBI:/config

  bitwarden:
    container_name: BitWarden
    image: bitwardenrs/server:1.17.0
    restart: unless-stopped
    ports:
      - 8083:80
    environment:
      - ADMIN_TOKEN=random_token # High recommended that you generate a random token by typing openssl rand -base64 48 on the terminal
    volumes:
      - bitwarden_data:/data

volumes:
  portainer_data:
  bitwarden_data:
