# Programer: Pineapple
# 11/11/2020

version: "3.8"
services:
  agent:
    image: portainer/agent:2.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.0.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  plex:
    #container_name: Plex
    image: linuxserver/plex:version-1.20.2.3402-0fec14d92
    ##restart: unless-stopped
    #network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=america/chicago
    volumes:
      - /home/Data/Config/Plex:/config
      - /home/Data/Storage/Tv:/tv
      - /home/Data/Storage/Movies:/movies
    ports:
      - 32400:32400/tcp
    deploy:
      mode: replicated
      replicas: 1

  tautulli:
    #container_name: Tautulli
    image: linuxserver/tautulli:7b936fd6-ls1
    #restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - TZ=america/chicago
    #  - TZ=america/new_york
    volumes:
      - /home/Data/Config/Tautulli:/config
      - /home/Data/Config/Plex/Library/Application Support/Plex Media Server/Logs/:/logs
    ports:
      - 8181:8181
    deploy:
      mode: replicated
      replicas: 1

  ombi:
    #container_name: OMBI
    image: linuxserver/ombi:version-v4.0.530
    #restart: unless-stopped
    ports:
      - 3579:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/chicago
    #  - TZ=america/new_york
    volumes:
      - /home/Data/Config/OMBI:/config
    deploy:
      mode: replicated
      replicas: 1

  swag:
    #container_name: SWAG
    image: linuxserver/swag:version-1.9.0
    #restart: unless-stopped
    ports:
      #- 8081:80
      - 4343:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/chicago
      - URL=yourdomain.localhost
      - SUBDOMAINS=www,
      - VALIDATION=dns
      #- DNSPLUGIN=cloudflare #optional
      #- PROPAGATION= #optional
      #- DUCKDNSTOKEN= #optional
      #- EMAIL= #optional
      #- ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS= #optional
      #- STAGING=false #optional
      #- MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - /home/Data/Config/Nginx:/config
    deploy:
      mode: replicated
      replicas: 1

  bitwarden:
    #container_name: BitWarden
    image: bitwardenrs/server:1.17.0
    #restart: unless-stopped
    ports:
      - 8083:80
      #- 8083:443
    environment:
      - DOMAIN='https://yourdomain.server.local/'
      - ADMIN_TOKEN=random_token # High recommended that you generate a random token by typing openssl rand -base64 48 on the terminal
    volumes:
      - bitwarden_data:/data
    deploy:
      mode: replicated
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
  bitwarden_data:
