# Programer: Pineapple
# 11/11/2020

version: "3.8"
services:
  agent:
    image: portainer/agent:2.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.0.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  wireguard:
    image: linuxserver/wireguard:version-v1.0.20200827
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/chicago
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - SERVERPORT=51820 #optional
    volumes:
      - /home/Data/Config/WireGuard:/config
      - /lib/modules:/lib/moduless
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      mode: replicated
      replicas: 1

  jenkins:
    image: jenkins/jenkins:2.249.3-lts-alpine
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8080

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
  jenkins_data:
