# Programer: Pineapple
# 11/11/2020

version: "3.8"
services:
  plex:
    image: linuxserver/plex:version-1.20.2.3402-0fec14d92
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=america/chicago
    volumes:
      - /home/Data/Config/Plex:/config
      - /home/Data/Storage/Tv:/tv
      - /home/Data/Storage/Movies:/movies
    ports:
      - 32400:32400/tcp
    deploy:
      mode: replicated
      replicas: 1

  tautulli:
    image: linuxserver/tautulli:7b936fd6-ls1
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - TZ=america/chicago
    #  - TZ=america/new_york
    volumes:
      - /home/Data/Config/Tautulli:/config
      - /home/Data/Config/Plex/Library/Application Support/Plex Media Server/Logs/:/logs
    ports:
      - 8181:8181
    deploy:
      mode: replicated
      replicas: 1

  ombi:
    image: linuxserver/ombi:version-v4.0.530
    ports:
      - 3579:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/chicago
    #  - TZ=america/new_york
    volumes:
      - /home/Data/Config/OMBI:/config
    deploy:
      mode: replicated
      replicas: 1
