# Programer: Pineapple
# 11/11/2020

version: "3.8"
services:
  nextcloud:
    image: linuxserver/nextcloud:version-20.0.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/chicago
    volumes:
      - /home/Data/Config/NextCloud:/config
      - /home/Data/Storage/Backup:/Backup
    ports:
      - 4443:443/tcp
    deploy:
      mode: replicated
      replicas: 1
# NEED TO ADD BITWARDEN HERE
